# Generated by Django 5.2.7 on 2025-12-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=10, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_por_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_por_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_validade', models.DateField()),
            ],
        ),
    ]
