# Generated by Django 5.2.7 on 2025-12-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acougue', '0002_venda_itemvenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
